version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  test:
    build: .
    volumes:
      - .:/app
    command: pytest